config/routes.rb
Rails.application.routes.draw do

root  'users#index'
get 'users/signup'

  

  resources :users

  resources :sessions, only:[:create]
  
  get 'movie/list'

  get 'movie/new'
  get 'movie/edit'
  patch 'movie/update'
  get 'movie/update'
  get 'movie/delete'
  get 'movie/show_categories'

  get 'movie/show'
post 'movie/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates  :name, :email, presence: true
  validates :email, format: { with:  VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController

def list
    @movies = Movie.all


end

def show

    @movie = Movie.find(params[:id])

end

def new

    @movie = Movie.new
    @categories = Category.all

    

end

def movie_params
params.require(:movies).permit(:title, :year, :category_id, :price)

 end

def create

    @movie = Movie.new(movie_params)


    if  @movie.save

        redirect_to :action =>'list'

    else 
        @categories = Category.all
        
    end
end


def edit

    @movie =Movie.find(params[:id])

    @categories = Category.all

end 

def movie_params
    params.require(:movies).permit(:title, :year, :category_id, :price)

end

def update
  
   @movie = Movie.find(params[:id]) 

    if @movie.update_attributes(movie_params)

        redirect_to :action => 'show'

    else
        @categories = Category.all
        render :action => 'edit'

    end 
end

def delete

    Movie.find(params[:id]).destroy

    redirect_to :action => 'list'
end
def show_categories

    @category =Category.find(params[:id])
end


  def movie_params
    params.require(:movies).permit(:title, :year, :category_id, :price)

end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def create

        user=User.find_by(email: params[:email] )
          if user && user.authenticate(params[:password])
            session[:user_id]= user.id
            redirect_to movie_list_path

          else
            flash[:errors] = ["invalid commbination"]
            redirect_back(fallback_location: root_path)
          end


    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



    def index

    end 
    
    
    def signup
    end


    def create
        user = User.new(user_params)
        if user.save
            session[:user_id]= user.id
            redirect_to :action =>'index'
        else
           flash[:errors] = user.errors.full_messages
            redirect_to :action =>'index'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JorahApp</title>
    <%= csrf_meta_tags %>

    
   
  </head>

  <body>
   <div class="container"> <%= yield %> </div>
   <%= yield %>
  </body>
</html>

app/views/movie/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      
      <nav class="nav nav-masthead justify-content-center" style="padding: 10px">
      <button type="button" class="btn btn-secondary">   <%=link_to "Home", movie_list_path  %>   </button>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">


  <h1>Edit movie Detail</h1>

 

<%= form_for @movie, :url =>{:action =>"update", :id =>@movie} do |f| %>

 

<p>Title: <%= f.text_field 'title' %></p>

<p>Price: <%= f.text_field  'price' %></p>

<p>Subject: <%= f.collection_select :category_id,Category.all, :id, :name %></p>



 

<p>Year: <%= f.text_field 'year' %></p>

<%= f.submit "Save changes" %>

<% end %>

 
  
  




    
      <a href="#" class="btn btn-lg btn-secondary"> <%= link_to "Add new movie", {:action =>'new' } %>  </a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/movie/list.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }



    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      
      <nav class="nav nav-masthead justify-content-center" style="padding: 10px">
      
          <button type="button" class="btn btn-secondary">   <%=link_to "log out", root_path  %>   </button>
          
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">









  <main role="main" class="container" >


        
              
  <div class="row text-center pt-5" style="margin-top:0px"  >
  
  
      
  <div class="col-sm-12 col-lg">
  
  
  </div>
  
  
 
  
  <div class="col-sm-12 col-lg">


  <table>



  <% if @movies.blank? %>

  <p>There are not any movie currently in the system.</p>
  
  <% else %>
  
  <p>These are the current movie in our system</p>


  <tr>
    <th>Title</th>
   
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tr>

  <% @movies.each do |c| %>
    <td><%= link_to c.title, {:action => 'show', :id => c.id} -%></td>
    
    <td> <%= link_to 'Edit', {:action => "edit", :id => c.id} %> </td>
    <td><%= link_to "Delete" , {:action => 'delete', :id => c.id}, :confirm => "are you sure to delete?" %></td>
  </tr>
  
 
  <% end %>
 
</table>







 <%= link_to "Add new movie", {:action =>'new' } %>  
<% end %>
  
  
  </div>




  <div class="col-sm-12 col-lg">



  
  
  
  </div>

 


 
  
  
  
  </div>
  
  
  
  
  
  </main>










  
  




    
      
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
     
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/movie/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      
      <nav class="nav nav-masthead justify-content-center" style="padding: 10px">
      <button type="button" class="btn btn-secondary">   <%=link_to "Home", movie_list_path  %>   </button>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">






  <main role="main" class="container" >


        
              
  <div class="row text-center pt-5" style="margin-top:0px"  >
  
  
      
  <div class="col-sm-12 col-lg">
  
  
  </div>
  
  
  <div class="col-sm-12 col-lg">
  
  
  
  <h1>Add new movie</h1>
  
   
  
  <%= form_tag :action => 'create' do %>
  
  <p><label for = "movie_title">Title</label>:
  
   
  
  <%= text_field 'movies', 'title' %></p>
  
  <p><label for = "movie_price">Price</label>:
  
   
  
  <%= text_field 'movies', 'price' %></p>
  
  <p><label for ="movie_category_id">categorie</label>:
  
   
  
  <%= collection_select(:movies, :category_id,@categories, :id, :name, prompt: true) %></p>
  
  <p><label for ="movie_year">year:</label><br/>
  
   
  
  <%= text_field 'movies', 'year' %></p>
  
  <%= submit_tag "Create" %>
  
   
  
  <% end -%>
  
  <%= link_to 'Back', {:action => 'list'} %>
  
  
  
  
    
    
    
    
  
  
  
  
      
        <a href="#" class="btn btn-lg btn-secondary"> <%= link_to "Add new movie", {:action =>'new' } %>  </a>
      </p>
  
  
  </div>
  
  
  
  <div class="col-sm-12 col-lg">
  
  
  </div>
  
  
  
  
  </div>
  
  </div>
  
  










  


  
  
  
  
  
  
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/movie/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      
      <nav class="nav nav-masthead justify-content-center" style="padding: 10px">
      <button type="button" class="btn btn-secondary">   <%=link_to "Home", movie_list_path  %>   </button>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">







  <main role="main" class="container" >


        
              
  <div class="row text-center pt-5" style="margin-top:0px"  >


      
  <div class="col-sm-12 col-lg">


  </div>


  <div class="col-sm-12 col-lg">



  <h1><%= @movie.title %></h1>

 

<p>

   <strong>Price: </strong> $<%= @movie.price%><br />
   <strong>Year: </strong> $<%= @movie.year%><br />

   <strong>Category :</strong> <%= link_to @movie.category.name, :action => "show_categories", :id => @movie.category.id %><br />

   <strong>Created Date:</strong> <%=@movie.created_at %><br />

</p>

 

<p><%= @movie.year %></p>

 

<hr />

 

<%= link_to 'Back', {:action => 'list'} %>



 
  
  




  </div>



  <div class="col-sm-12 col-lg">


  </div>




  </div>

</div>























  


    
      
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
     
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


      body {


      }
.login-box 
   { width: 280px;
   position: absolute;



}

    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      
      <nav class="nav nav-masthead justify-content-center" style="padding: 10px">
       
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">


  






  <main role="main" class="container" >


        
              
  <div class="row text-center pt-5" style="margin-top:0px"  >



  <div class="col-sm-12 col-lg">


  <% if flash[:errors] %>
  <% flash[:errors].each do |e| %>

    <p> <%= e %> </p>

    <% end %>
    <% end %>


  
  
  </div>


  
  
      
  <div class="col-sm-12 col-lg">

  

 

  


  
  </div>
  
  
 
  
  <div class="col-sm-12 col-lg">
 <div class="login-box"
  <form>
  <%= form_tag sessions_path do %>
    <div class="form-group">
   
    <label for="exampleInputEmail1">Email address</label>

    <div class="form-control" >
    <%= email_field_tag :email %>

    </div>
    </div>
    
  
  <div class="form-group">
  
  <label for="exampleInputEmail1">Email address</label>


  <div class="form-control" >
   
    <%= password_field_tag :password %>
   </div> 
    
</div>
    
    
    
    <button type="button" class="btn btn-secondary">   <%=link_to 'sign up', {:action =>'signup'} %>  </button>
    <button type="button" class="btn btn-secondary">   <%= submit_tag "Sign in" %>  </button>
    
    <% end %>

  </form>

  </div>
  




  
  </div>



  
  
  
  <div class="col-sm-12 col-lg">

  

 

  


  
  </div>
 


 
  
  
  
  </div>
  
  
  
  
  
  </main>










  
  




    
      
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
     
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>












   